name: Build and Push Docker

on:
  push:
    branches:
      - master

jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:

    - name: chekout code
      uses: actions/chekout@v3

    - name: Login into Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build Docker Image
      run: |
        docker bulid \
          -t vishwanathmalide/devops-collage-form:v1.1.0 
          .
    - name: Push docker image to docker Hub
      run: |
        docker push vishwanathmalide/devops-collage-form:v1.1.0 
